SeeSpot/SeeSpot/Controllers/BreedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SeeSpot.Data;
using SeeSpot.Models;
using SeeSpot.ViewModels;

namespace SeeSpot.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BreedController : Controller
    {
        
        public IActionResult Index()
        {
            List<Breed> breeds;
            breeds = context.Breeds.ToList();
            return View(breeds);
        }

        private readonly Data.SeeSpotDbContext context;

        public BreedController(SeeSpotDbContext dbContext)
        {
            context = dbContext;
        }



        public IActionResult Add()
        {
            AddBreedViewModel addBreedViewModel = new AddBreedViewModel();
            return View(addBreedViewModel);

        }
        [HttpPost]
        public IActionResult Add(AddBreedViewModel addBreedViewModel)
        {
            if (ModelState.IsValid)
            {
                // Add the new cheese to my existing cheeses
                Breed newBreed = new Breed
                {
                    Name = addBreedViewModel.Name,
                };

                context.Breeds.Add(newBreed);
                context.SaveChanges();

                return Redirect("/Breed");
            }

            return View(addBreedViewModel);
        }
        public IActionResult Delete()
        {
            List<Breed> breeds = context.Breeds.ToList();
            return View(breeds);
        }

        [HttpPost]
        public IActionResult Delete(int[] categoryIds)
        {
            foreach (int categoryId in categoryIds)
            {
                Breed theBreed = context.Breeds.Single(c => c.ID == categoryId);
                context.Breeds.Remove(theBreed);
            }
            context.SaveChanges();
            return Redirect("/Breed");
        }
    }
}

SeeSpot/SeeSpot/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SeeSpot.Data;
using SeeSpot.Models;
using SeeSpot.ViewModels;

namespace SeeSpot.Controllers
{
    public class PetController : Controller
    {
        private readonly SeeSpotDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IHostingEnvironment hostingEnvironment;

        public PetController(SeeSpotDbContext dbContext,
                            IHostingEnvironment hostingEnvironment, UserManager<ApplicationUser> userManager)

        {
            context = dbContext;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;

        }
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);// will give the user's userId
            var userName = User.FindFirstValue(ClaimTypes.Name); // will give the user's userName

            ApplicationUser applicationUser = await userManager.GetUserAsync(User);
            string userEmail = applicationUser?.Email; // will give the user's Email
            var OwnerPets = from m in context.Pets
                            where m.OwnerId == userId
                            select m;
            ViewBag.OwnerPets = OwnerPets;
            return View();
        }
        public IActionResult Add()
        {
            AddPetViewModel addPetViewModel = new AddPetViewModel(context.Breeds.ToList());
            return View(addPetViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddPetViewModel model)
        {

            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                //Breed newBreed =
                //    context.Breeds.Single(c => c.ID == model.BreedID);

                // Add the new cheese to my existing cheeses
                Pet newPet = new Pet
                {
                    Name = model.Name,
                    OwnerId = model.OwnerId,
                    Weight = model.Weight,
                    BreedName = model.BreedName,
                    PhotoPath = uniqueFileName,
                    Gender = model.Gender,
                    Color = model.Color,
                    Birthday = model.Birthday,
                    Microchipped = model.Microchipped,
                    Fixed = model.Fixed
                };

                context.Pets.Add(newPet);
                context.SaveChanges();

                return Redirect("/Pet");
            }

            return View(model);
        }

        public ActionResult Profile(int ID)
        {
            
            Pet pet = context.Pets.Find(ID);
            ProfileViewModel profileViewModel = new ProfileViewModel
            {
                ID = pet.ID,
                Name = pet.Name,
                Birthday = pet.Birthday,
                Color = pet.Color,
                Weight = pet.Weight,
                Gender = pet.Gender,
                BreedName = pet.BreedName,                
                Microchipped = pet.Microchipped,
                Fixed = pet.Fixed,
                ExistingPhotoPath = pet.PhotoPath,
                
                
            };
            return View(profileViewModel);
            
            
        }

        [HttpGet]
        public ActionResult EditProfile(int ID)
        {

            Pet pet = context.Pets.Find(ID);
            EditProfileViewModel editProfileViewModel = new EditProfileViewModel(context.Breeds.ToList())
            {
                ID = pet.ID,
                Name = pet.Name,
                Birthday = pet.Birthday,
                Color = pet.Color,
                Weight = pet.Weight,
                Gender = pet.Gender,
                BreedName = pet.BreedName,
                Microchipped = pet.Microchipped,
                Fixed = pet.Fixed,
                ExistingPhotoPath = pet.PhotoPath
                
            };
            return View(editProfileViewModel);
        }

        [HttpPost]
        public IActionResult EditProfile(EditProfileViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                
               
                Pet pet = context.Pets.Find(model.ID);
                pet.Name = model.Name;
                pet.Birthday = model.Birthday;
                pet.Color = model.Color;
                pet.Weight = model.Weight;
                pet.Gender = model.Gender;
                pet.BreedName = model.BreedName;
                pet.Microchipped = model.Microchipped;
                pet.Fixed = model.Fixed;
                pet.PhotoPath = model.ExistingPhotoPath;

                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    pet.PhotoPath = ProcessUploadedFile(model);

                }

                

                context.Update(pet);
                context.SaveChanges();
                return RedirectToAction("index");
            }
            return View(model);
        }

        private string ProcessUploadedFile(AddPetViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
        public async Task<IActionResult> Delete(int id)
        {
            var pet = await context.Pets.FindAsync(id);
            context.Pets.Remove(pet);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

SeeSpot/SeeSpot/Controllers/WalkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SeeSpot.Data;
using SeeSpot.Models;
using SeeSpot.ViewModels;

namespace SeeSpot.Controllers
{

    public class WalkController : Controller
    {
        private readonly SeeSpotDbContext context;

        public WalkController(SeeSpotDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            IList<Walk> walks = context.Walks.ToList();

            return View(walks);
        }
        public ActionResult Details(int ID)
        {

            Walk walk = context.Walks.Find(ID);
            DetailsWalkViewModel detailsWalkViewModel = new DetailsWalkViewModel
            {
                ID = walk.ID,
                Distance = walk.Distance,
                Poop = walk.Poop,
                Pee = walk.Pee,
                Date = walk.Date,
                Time = walk.Time,
                Notes = walk.Notes



            };
            return View(detailsWalkViewModel);

        }


        public IActionResult Add()
        {
            AddWalkViewModel addWalkViewModel = new AddWalkViewModel();
            return View(addWalkViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddWalkViewModel addWalkViewModel)
        {

            if (ModelState.IsValid)
            {
                
                
                Walk newWalk = new Walk
                {
                    Distance = addWalkViewModel.Distance,
                    Poop = addWalkViewModel.Poop,
                    Pee = addWalkViewModel.Pee,
                    Date = addWalkViewModel.Date,
                    Time = addWalkViewModel.Time,
                    Notes = addWalkViewModel.Notes,


                };

                context.Walks.Add(newWalk);
                context.SaveChanges();

                return Redirect("/Walk");
            }

            return View(addWalkViewModel);
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {

            Walk walk = context.Walks.Find(ID);
            EditWalkViewModel editWalkViewModel = new EditWalkViewModel
            {
                ID = walk.ID,
                Distance = walk.Distance,
                Poop = walk.Poop,
                Pee = walk.Pee,
                Date = walk.Date,
                Time = walk.Time,
                Notes = walk.Notes,
                

            };
            return View(editWalkViewModel);
        }

        [HttpPost]
        public IActionResult Edit(EditWalkViewModel model)
        {

            if (ModelState.IsValid)
            {


                Walk walk = context.Walks.Find(model.ID);
                walk.ID = model.ID;
                walk.Distance = model.Distance;
                walk.Poop = model.Poop;
                walk.Pee = model.Pee;
                walk.Date = model.Date;
                walk.Time = model.Time;
                walk.Notes = model.Notes;

                context.Update(walk);
                context.SaveChanges();
                return RedirectToAction("index");
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var walk = await context.Walks.FindAsync(id);
            context.Walks.Remove(walk);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

SeeSpot/SeeSpot/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to nagivate to the home page
</a>

SeeSpot/SeeSpot/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInMgr;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeeSpot</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SeeSpot</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Walk" asp-action="Index">Walks</a>
                        </li>
                        @if (SignInMgr.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListRoles">Manager Roles</a>
                            </li>
                        }
                        @if (SignInMgr.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Breed" asp-action="Index">Manage Breeds</a>
                            </li>
                        }
                        @if (SignInMgr.IsSignedIn(User))
                        {
                            <li class="nav-item ml-auto">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name

                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        @*<li>
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Account" asp-action="Logout">@User.Identity.Name, Logout</a>
            }
            else
            {
                <a asp-controller="Account" asp-action="Login">Login</a>
            }


        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SeeSpot - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>